import React from "react";
import { Container } from "@material-ui/core";

import UnderDev from "app/UnderDevelopment";

const createdQuote = {
  lines: [
    [
      {
        ItemId: "62138a3f3e1107765af0388f",
        ItemObject: {
          totalCost: 0,
          id: "62138a3f3e1107765af0388f",
          no: "test-1",
          name: "test device 01",
          approvedForSale: false,
          obsolete: false,
          rndOnly: false,
          archived: false,
          nonInventoryItem: false,
          dontTrackQoh: false,
          dontOrderOnPOs: false,
          engineeringApproval: false,
          bom: false,
          option: false,
          invalidCost: false,
          taxable: false,
          device: true,
          isUnit: false,
          overrideUse: false,
          onOrderQty: 0,
          onHandQty: 0,
          allocatedQty: 0,
          availableQty: 0,
          totalQty: 0,
          usedInQuarter: 0,
          usedInHalf: 0,
          usedInYear: 0,
          qohMismatch: false,
          notShippable: false,
          shippingChecklistRequired: false,
          shippableOnBOM: false,
          assembly: false,
          manufacturingTime: 0,
          evaluateTime: 0,
          testTime: 0,
          laborCost: 0,
          pricing: [],
          createdAt: 1645447743570,
          updatedAt: 1645447753757,
          __v: 0,
          serviceClassses: [],
        },
        qty: 1,
        price: 250,
        unit: true,
        standardWarranty: true,
        type: "device",
      },
    ],
    [
      {
        ItemId: "6214c70b56073675875df751",
        ItemObject: {
          id: "6214c70b56073675875df751",
          no: "test-item-1",
          name: "test Item 2",
          approvedForSale: false,
          obsolete: false,
          rndOnly: false,
          archived: false,
          nonInventoryItem: false,
          dontTrackQoh: false,
          dontOrderOnPOs: false,
          engineeringApproval: false,
          bom: false,
          option: false,
          invalidCost: false,
          taxable: false,
          device: true,
          isUnit: false,
          overrideUse: false,
          totalCost: 0,
          onOrderQty: 0,
          onHandQty: 0,
          allocatedQty: 0,
          availableQty: 0,
          totalQty: 0,
          usedInQuarter: 0,
          usedInHalf: 0,
          usedInYear: 0,
          qohMismatch: false,
          notShippable: false,
          shippingChecklistRequired: false,
          shippableOnBOM: false,
          assembly: false,
          manufacturingTime: 0,
          evaluateTime: 0,
          testTime: 0,
          laborCost: 0,
          pricing: [],
          createdAt: 1645528843310,
          updatedAt: 1645528843310,
          __v: 0,
          serviceClassses: [],
        },
        qty: 2,
        price: 150,
        unit: true,
        standardWarranty: true,
        type: "device",
      },
    ],
  ],
  location: "new york",
  salesperson: "62078de3c1a436adbfedaac8",
  leadTime: "5",
  note: "some notes",
  requesterName: "req name",
  requesterMail: "req meil",
  requesterPhone: "req phone",
  commissionLabel: "1",
  regularCommission: 5,
  overageCommission: 565,
};

const createdSO = {
  number: "123",
  QuoteId: "621bb6904555240f473c39f9",
  projectLocationlocation: "new york",
  lines: [
    [
      {
        id: "621bb6904555240f473c39fb",
        group: 1,
        line: 1,
        ItemId: "62138a3f3e1107765af0388f",
        qty: 5,
        price: 200,
        standardWarranty: true,
        unit: true,
        QuoteId: "621bb6904555240f473c39f9",
        createdAt: 1645983376834,
        updatedAt: 1645983376834,
        __v: 0,
        ItemObject: {
          id: "62138a3f3e1107765af0388f",
          no: "test-1",
          name: "test device 01",
          usedInQuarter: null,
          usedInHalf: null,
          usedInYear: null,
        },
        type: "device",
      },
    ],
    [
      {
        id: "621bb6904555240f473c39fd",
        group: 2,
        line: 1,
        ItemId: "621ba9e24555240f473c34d1",
        qty: 4,
        price: 150,
        standardWarranty: true,
        unit: true,
        QuoteId: "621bb6904555240f473c39f9",
        createdAt: 1645983376839,
        updatedAt: 1645983376839,
        __v: 0,
        ItemObject: {
          id: "621ba9e24555240f473c34d1",
          no: "item-test-1",
          name: "item test 1",
          usedInQuarter: null,
          usedInHalf: null,
          usedInYear: null,
        },
        type: "device",
      },
    ],
  ],
};

export default function Settings() {
  return (
    <Container>
      <UnderDev />
    </Container>
  );
}
